### ISSUE TITLE
Kathryn - fyi but on containercraft.io there is no way to contact anyone

### ISSUE THREAD

**Issue by bmullan** [containercraft/mini-stack#3]
I wanted to send you an email about my CIAB Remote Desktop System but your Github profile doesn't have an Email listed.

So I went to Containercraft.io 
If you click CONTACT it takes you to the bottom of the screen.

FYI ... but NONE of those contact methods work!   If you click email it does bring up my email client but there is NO "TO" address inserted into the email so NO one to send it to.

Clicking Twitter is more or less the same thing.

Just fyi... but it looks like there is no way anyone can contact you ?

So I am leaving this "issue" here as at least an attempt to let you know.

Brian

**Comment by KathrynMorgan** [comment]
Hey Brian, thanks for the note!

Actually I've been keeping an eye on your CIAB project and have been intending to reach out when mini-stack is just a bit more mature.

The CCIO ecosystem is just spinning up so most of those resources are incomplete as you discovered.

You are always welcome in the freenode #containercraft channel where I check for activity regularly until the rest of the resources & forum are spun up.
